language: "node_js"
node_js:
  - "4"
  - "6"
  - "8"

before_install:
 - "npm install istanbul -g"
 - "npm install coveralls -g"

script: "make ci-travis"

after_success:
  - "make submit-cov-to-coveralls"
